### ISSUE TITLE
I want to get the key release event in rviz::Tool class

### ISSUE THREAD

**Issue by lidongxu111** [DLR-RM/rosmc#1]
I want to get the key release event in rviz::Tool class

but the function processKeyEvent can only get pressed key event.

Is there any way to get released key event?

**Comment by ryosakagami** [comment]
Could you please ask this question to the rviz developers, e.g. https://github.com/ros-visualization/rviz?
I am not directly using the function to access the key event from Rviz in my development.

**Comment by lidongxu111** [comment]
ok,
thank you
